# Generated by Django 2.2.4 on 2019-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='end',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='start',
            field=models.FloatField(null=True),
        ),
    ]
