# Generated by Django 2.2.4 on 2019-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190906_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='node_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='RunNodes',
        ),
    ]
