# Generated by Django 2.2.4 on 2019-09-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190907_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
