# Generated by Django 2.2.4 on 2019-09-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='api_token',
            field=models.TextField(null=True),
        ),
    ]
