# Generated by Django 2.2.4 on 2020-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190907_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='updated',
            field=models.FloatField(null=True),
        ),
    ]
